const os = require("node:os")
console.group("╔══════════ informacion del sistema operativo 🚀 ═════════╗")
console.log(" - Nombre del sistema operativo: ", os.platform())
console.log(" - version del sistema operativo: ", os.release())
console.log(" - Arquitectura del sistema operativo: ", os.arch())
console.log(" - ubicacion del sistema operativo ", os.devNull())
console.log("- memoria libre: " ,os.freemem() / 1024 / 1024 )
console.log("- memoria total: ", os.totalmem() / 1024 / 1024)
console.log("- tiempo de uso de la computadora: ", os.uptime()/  60 / 60)
console.log("╔══════════ fin del sistema operativo ═════════")